//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveyval {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Surveyval.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Questionnaire-Manager ähnelt.
        /// </summary>
        internal static string ButtonDesign {
            get {
                return ResourceManager.GetString("ButtonDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The question: ähnelt.
        /// </summary>
        internal static string DesignAddQuestion1 {
            get {
                return ResourceManager.GetString("DesignAddQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die has been added to the questionnaire. ähnelt.
        /// </summary>
        internal static string DesignAddQuestion2 {
            get {
                return ResourceManager.GetString("DesignAddQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question added ähnelt.
        /// </summary>
        internal static string DesignAddQuestion3 {
            get {
                return ResourceManager.GetString("DesignAddQuestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add question ähnelt.
        /// </summary>
        internal static string DesignButtonAddQuestion {
            get {
                return ResourceManager.GetString("DesignButtonAddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string DesignButtonCancel {
            get {
                return ResourceManager.GetString("DesignButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete question ähnelt.
        /// </summary>
        internal static string DesignButtonDelQuestion {
            get {
                return ResourceManager.GetString("DesignButtonDelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete questionnaire ähnelt.
        /// </summary>
        internal static string DesignButtonDelQuestionnaire {
            get {
                return ResourceManager.GetString("DesignButtonDelQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New question ähnelt.
        /// </summary>
        internal static string DesignButtonNewQuestion {
            get {
                return ResourceManager.GetString("DesignButtonNewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New questionnaire ähnelt.
        /// </summary>
        internal static string DesignButtonNewQuestionnaire {
            get {
                return ResourceManager.GetString("DesignButtonNewQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove question ähnelt.
        /// </summary>
        internal static string DesignButtonRemoveQuestion {
            get {
                return ResourceManager.GetString("DesignButtonRemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string DesignButtonSave {
            get {
                return ResourceManager.GetString("DesignButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes ähnelt.
        /// </summary>
        internal static string DesignCancelChanges1 {
            get {
                return ResourceManager.GetString("DesignCancelChanges1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save your changes to ähnelt.
        /// </summary>
        internal static string DesignCancelChanges2 {
            get {
                return ResourceManager.GetString("DesignCancelChanges2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete question ähnelt.
        /// </summary>
        internal static string DesignDeleteQuestion1 {
            get {
                return ResourceManager.GetString("DesignDeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the follwing question from the catalog: ähnelt.
        /// </summary>
        internal static string DesignDeleteQuestion2 {
            get {
                return ResourceManager.GetString("DesignDeleteQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (You won´t be able to use it anymore) ähnelt.
        /// </summary>
        internal static string DesignDeleteQuestion3 {
            get {
                return ResourceManager.GetString("DesignDeleteQuestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question-Catalog ähnelt.
        /// </summary>
        internal static string DesignGroupBoxQuestionCatalog {
            get {
                return ResourceManager.GetString("DesignGroupBoxQuestionCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Questionnaire-Catalog ähnelt.
        /// </summary>
        internal static string DesignGroupBoxQuestionnaireCatalog {
            get {
                return ResourceManager.GetString("DesignGroupBoxQuestionnaireCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Questions catalog ähnelt.
        /// </summary>
        internal static string DesignLabelCatalog {
            get {
                return ResourceManager.GetString("DesignLabelCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Included questions ähnelt.
        /// </summary>
        internal static string DesignLabelIncluded {
            get {
                return ResourceManager.GetString("DesignLabelIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string DesignLabelName {
            get {
                return ResourceManager.GetString("DesignLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        internal static string DesignListViewTextLabel {
            get {
                return ResourceManager.GetString("DesignListViewTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Questionnaire ähnelt.
        /// </summary>
        internal static string DesignNewQuestionnaireText {
            get {
                return ResourceManager.GetString("DesignNewQuestionnaireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The question: ähnelt.
        /// </summary>
        internal static string DesignRemoveQuestion1 {
            get {
                return ResourceManager.GetString("DesignRemoveQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die has been removed from the questionnaire. ähnelt.
        /// </summary>
        internal static string DesignRemoveQuestion2 {
            get {
                return ResourceManager.GetString("DesignRemoveQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save questionnaire ähnelt.
        /// </summary>
        internal static string DesignSave {
            get {
                return ResourceManager.GetString("DesignSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die has been saved. ähnelt.
        /// </summary>
        internal static string DesignSaveDone {
            get {
                return ResourceManager.GetString("DesignSaveDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A questionnaire with that name already exists. Do you want to override it? ähnelt.
        /// </summary>
        internal static string DesignSaveExists {
            get {
                return ResourceManager.GetString("DesignSaveExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The questionnaire: ähnelt.
        /// </summary>
        internal static string DesignSaveNoQuestions1 {
            get {
                return ResourceManager.GetString("DesignSaveNoQuestions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die does not contain any questions. Do you want to save it anyway? ähnelt.
        /// </summary>
        internal static string DesignSaveNoQuestions2 {
            get {
                return ResourceManager.GetString("DesignSaveNoQuestions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Questionnaire-Manager ähnelt.
        /// </summary>
        internal static string DesignTitle {
            get {
                return ResourceManager.GetString("DesignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Surveyval ähnelt.
        /// </summary>
        internal static string MainWindow {
            get {
                return ResourceManager.GetString("MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string NewQuestionButtonCancel {
            get {
                return ResourceManager.GetString("NewQuestionButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string NewQuestionButtonSave {
            get {
                return ResourceManager.GetString("NewQuestionButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The question you entered is similar to the following question: ähnelt.
        /// </summary>
        internal static string NewQuestionExists1 {
            get {
                return ResourceManager.GetString("NewQuestionExists1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save it anyway? ähnelt.
        /// </summary>
        internal static string NewQuestionExists2 {
            get {
                return ResourceManager.GetString("NewQuestionExists2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question exists ähnelt.
        /// </summary>
        internal static string NewQuestionExists3 {
            get {
                return ResourceManager.GetString("NewQuestionExists3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Answer type ähnelt.
        /// </summary>
        internal static string NewQuestionGroupBoxAnswer {
            get {
                return ResourceManager.GetString("NewQuestionGroupBoxAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        internal static string NewQuestionLabelText {
            get {
                return ResourceManager.GetString("NewQuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string NewQuestionnaireButtonCancel {
            get {
                return ResourceManager.GetString("NewQuestionnaireButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string NewQuestionnaireButtonSave {
            get {
                return ResourceManager.GetString("NewQuestionnaireButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string NewQuestionnaireLabelName {
            get {
                return ResourceManager.GetString("NewQuestionnaireLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name... ähnelt.
        /// </summary>
        internal static string NewQuestionnaireTextBoxName {
            get {
                return ResourceManager.GetString("NewQuestionnaireTextBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Questionnaire ähnelt.
        /// </summary>
        internal static string NewQuestionnaireTitle {
            get {
                return ResourceManager.GetString("NewQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choice ähnelt.
        /// </summary>
        internal static string NewQuestionRadioChoice {
            get {
                return ResourceManager.GetString("NewQuestionRadioChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        internal static string NewQuestionRadioText {
            get {
                return ResourceManager.GetString("NewQuestionRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question saved ähnelt.
        /// </summary>
        internal static string NewQuestionSaved1 {
            get {
                return ResourceManager.GetString("NewQuestionSaved1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The question has been saved. ähnelt.
        /// </summary>
        internal static string NewQuestionSaved2 {
            get {
                return ResourceManager.GetString("NewQuestionSaved2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the question... ähnelt.
        /// </summary>
        internal static string NewQuestionTextBoxText {
            get {
                return ResourceManager.GetString("NewQuestionTextBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New question ähnelt.
        /// </summary>
        internal static string NewQuestionTitle {
            get {
                return ResourceManager.GetString("NewQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string SelectionButtonCancel {
            get {
                return ResourceManager.GetString("SelectionButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string SelectionButtonDelete {
            get {
                return ResourceManager.GetString("SelectionButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        internal static string SelectionButtonLoad {
            get {
                return ResourceManager.GetString("SelectionButtonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new ähnelt.
        /// </summary>
        internal static string SelectionButtonNew {
            get {
                return ResourceManager.GetString("SelectionButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The questionnaire has been deleted. ähnelt.
        /// </summary>
        internal static string SelectionDeleteDeleted {
            get {
                return ResourceManager.GetString("SelectionDeleteDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the following questionnaire? ähnelt.
        /// </summary>
        internal static string SelectionDeleteText {
            get {
                return ResourceManager.GetString("SelectionDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete questionnaire ähnelt.
        /// </summary>
        internal static string SelectionDeleteTitle {
            get {
                return ResourceManager.GetString("SelectionDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Questionnaire ähnelt.
        /// </summary>
        internal static string SelectionTitle {
            get {
                return ResourceManager.GetString("SelectionTitle", resourceCulture);
            }
        }
    }
}
